import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { Config } from "../config.js";
import { registerVaultRead } from "./vault_read.js";
import { registerVaultList } from "./vault_list.js";
import { registerVaultWrite } from "./vault_write.js";
import { registerVaultPatch } from "./vault_patch.js";
import { registerVaultCreateFolder } from "./vault_create_folder.js";
import { registerVaultDelete } from "./vault_delete.js";
import { registerVaultReindex } from "./vault_reindex.js";
import { registerVaultMove } from "./vault_move.js";
import { registerVaultMoveFolder } from "./vault_move_folder.js";
import { registerVaultDeleteFolder } from "./vault_delete_folder.js";
import { registerVaultLinks } from "./vault_links.js";
import { registerVaultFrontmatter } from "./vault_frontmatter.js";
import { registerVaultSearch } from "./vault_search.js";
import { registerVaultDiff } from "./vault_diff.js";
import { registerVaultSnapshot } from "./vault_snapshot.js";
import { registerVaultQuery } from "./vault_query.js";
import { registerVaultReadMultiple } from "./vault_read_multiple.js";
import { registerVaultStats } from "./vault_stats.js";
import { registerVaultTags } from "./vault_tags.js";
import { registerVaultOutline } from "./vault_outline.js";
import { registerVaultResolveEmbeds } from "./vault_resolve_embeds.js";
import { registerVaultObsidianUrl } from "./vault_obsidian_url.js";
import { registerVaultBatch } from "./vault_batch.js";

export function registerAllTools(server: McpServer, config: Config): void {
  registerVaultRead(server, config);
  registerVaultList(server, config);
  registerVaultWrite(server, config);
  registerVaultPatch(server, config);
  registerVaultCreateFolder(server, config);
  registerVaultDelete(server, config);
  registerVaultReindex(server, config);
  registerVaultMove(server, config);
  registerVaultMoveFolder(server, config);
  registerVaultDeleteFolder(server, config);
  registerVaultLinks(server, config);
  registerVaultFrontmatter(server, config);
  registerVaultSearch(server, config);
  registerVaultDiff(server, config);
  registerVaultSnapshot(server, config);
  registerVaultQuery(server, config);
  registerVaultReadMultiple(server, config);
  registerVaultStats(server, config);
  registerVaultTags(server, config);
  registerVaultOutline(server, config);
  registerVaultResolveEmbeds(server, config);
  registerVaultObsidianUrl(server, config);
  registerVaultBatch(server, config);
}
